#! /usr/bin/env python
#
# Support module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    Mar 03, 2018 05:47:55 PM


import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

def set_Tk_var():
    global RGBW_R
    RGBW_R = StringVar()
    global RGB_R
    RGB_R = DoubleVar()
    global RGBW_G
    RGBW_G = StringVar()
    global RGB_G
    RGB_G = DoubleVar()
    global RGBW_B
    RGBW_B = StringVar()
    global RGB_B
    RGB_B = DoubleVar()
    global RGBW_W
    RGBW_W = DoubleVar()
    global RGBDim_Dim
    RGBDim_Dim = DoubleVar()
    global RGB_useDim
    RGB_useDim = StringVar()
    global XYZ_X
    XYZ_X = StringVar()
    global XYZ_Y
    XYZ_Y = StringVar()
    global XYZ_Z
    XYZ_Z = StringVar()
    global Yxy_Y
    Yxy_Y = StringVar()
    global Yxy_x
    Yxy_x = StringVar()
    global Yxy_y
    Yxy_y = StringVar()
    global HSV_H
    HSV_H = StringVar()
    global HSV_S
    HSV_S = StringVar()
    global HSV_V
    HSV_V = StringVar()
    global HSL_H
    HSL_H = StringVar()
    global HSL_S
    HSL_S = StringVar()
    global HSL_L
    HSL_L = StringVar()
    global CLuv_L
    CLuv_L = StringVar()
    global CLuv_u
    CLuv_u = StringVar()
    global CLuv_v
    CLuv_v = StringVar()
    global CLCHab_L
    CLCHab_L = StringVar()
    global CLCHab_C
    CLCHab_C = StringVar()
    global CLCHab_H
    CLCHab_H = StringVar()
    global HLab_L
    HLab_L = StringVar()
    global HLab_a
    HLab_a = StringVar()
    global HLab_b
    HLab_b = StringVar()
    global CLab_L
    CLab_L = StringVar()
    global CLab_a
    CLab_a = StringVar()
    global CLab_b
    CLab_b = StringVar()
    global CMY_C
    CMY_C = StringVar()
    global CMY_M
    CMY_M = StringVar()
    global CMY_Y
    CMY_Y = StringVar()
    global CMYK_C
    CMYK_C = StringVar()
    global CMYK_M
    CMYK_M = StringVar()
    global CMYK_Y
    CMYK_Y = StringVar()
    global CMYK_K
    CMYK_K = StringVar()
    global colHTML
    colHTML = StringVar()
    global colCSS
    colCSS = StringVar()
    global colWebSafe
    colWebSafe = StringVar()
    global selectedButton
    selectedButton = StringVar()
    global RGB_useW
    RGB_useW = StringVar()
    global XYZ_scaled
    XYZ_scaled = StringVar()
    global RGBDim_adapt
    RGBDim_adapt = StringVar()
    global YUV_Y
    YUV_Y = StringVar()
    global YUV_U
    YUV_U = StringVar()
    global YUV_V
    YUV_V = StringVar()
    global YCbCr_Y
    YCbCr_Y = StringVar()
    global YCbCr_Cb
    YCbCr_Cb = StringVar()
    global YCbCr_Cr
    YCbCr_Cr = StringVar()
    global Yuv_Y
    Yuv_Y = StringVar()
    global Yuv_u
    Yuv_u = StringVar()
    global Yuv_v
    Yuv_v = StringVar()
    global CLCHuv_L
    CLCHuv_L = StringVar()
    global CLCHuv_C
    CLCHuv_C = StringVar()
    global CLCHuv_H
    CLCHuv_H = StringVar()

def TODO():
    print('ColorConverter_GUI_support.TODO')
    sys.stdout.flush()

def callback_blue(p1):
    print('ColorConverter_GUI_support.callback_blue')
    sys.stdout.flush()

def callback_dim(p1):
    print('ColorConverter_GUI_support.callback_dim')
    sys.stdout.flush()

def callback_green(p1):
    print('ColorConverter_GUI_support.callback_green')
    sys.stdout.flush()

def callback_red(p1):
    print('ColorConverter_GUI_support.callback_red')
    sys.stdout.flush()

def callback_white(p1):
    print('ColorConverter_GUI_support.callback_white')
    sys.stdout.flush()

def exit(p1):
    print('ColorConverter_GUI_support.exit')
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import ColorConverter_GUI
    ColorConverter_GUI.vp_start_gui()


