#############################################################################
# Generated by PAGE version 4.9
# in conjunction with Tcl version 8.6
set vTcl(timestamp) ""


set vTcl(actual_gui_bg) wheat
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) wheat
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #b2c9f4
set vTcl(analog_color_p) #eaf4b2
set vTcl(analog_color_m) #f4bcb2
set vTcl(active_fg) #111111
set vTcl(actual_gui_menu_active_bg)  #7f7f7f
set vTcl(active_menu_fg) #111111
#############################################################################
# vTcl Code to Load User Fonts

vTcl:font:add_font \
    "-family {Courier} -size 8 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font11
vTcl:font:add_font \
    "-family {Courier} -size 9 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font12
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top41
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    set site_3_0 $base.m42
    set site_3_0 $base.fra56
    set site_3_0 $base.cpd39
    set site_3_0 $base.cpd40
    set site_3_0 $base.cpd41
    set site_3_0 $base.cpd42
    set site_3_0 $base.cpd43
    set site_3_0 $base.cpd44
    set site_3_0 $base.cpd45
    set site_3_0 $base.cpd46
    set site_3_0 $base.cpd47
    set site_3_0 $base.cpd48
    set site_3_0 $base.cpd52
    set site_3_0 $base.cpd51
    set site_3_0 $base.cpd50
    set site_3_0 $base.cpd53
    set site_3_0 $base.cpd54
    set site_3_0 $base.cpd75
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# USER DEFINED PROCEDURES
#

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top41 {base} {
    if {$base == ""} {
        set base .top41
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m42" -background {#808080} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 900x530+140+190
    update
    # set in toplevel.wgt.
    global vTcl
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1000 600
    wm minsize $top 750 530
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    wm title $top "Color Converter by SMFSW"
    vTcl:DefineAlias "$top" "root" vTcl:Toplevel:WidgetProc "" 1
    menu $top.m42 \
        -activebackground {#c1ccd9} -activeforeground black \
        -background {#808080} -font TkMenuFont -foreground {#000000} \
        -tearoff 0 
    vTcl:DefineAlias "$top.m42" "men" vTcl:WidgetProc "" 1
    $top.m42 add cascade \
        -menu "$top.m42.men38" -activebackground {#808080} \
        -activeforeground {#111111} -background {#c1ccd9} \
        -font {-family {Segoe UI} -size 9 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground {#000000} -label File 
    set site_3_0 $top.m42
    menu $site_3_0.men38 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font {Tahoma 8} -foreground black -tearoff 0 
    $site_3_0.men38 add command \
        -activebackground {#808080} -activeforeground {#000000} \
        -background {#c1ccd9} -command TODO \
        -font {-family {Segoe UI} -size 9 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground {#000000} -label Open 
    $site_3_0.men38 add command \
        -activebackground {#808080} -activeforeground {#000000} \
        -background {#c1ccd9} -command exit(0) \
        -font {-family {Segoe UI} -size 9 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground {#000000} -label Quit 
    $top.m42 add command \
        -activebackground {#808080} -activeforeground {#000000} \
        -background {#c1ccd9} -command TODO \
        -font {-family {Segoe UI} -size 9 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground {#000000} -label Help 
    frame $top.fra45 \
        -borderwidth 2 -relief groove -background {#408080} -height 65 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 165 
    vTcl:DefineAlias "$top.fra45" "fraSampleColor" vTcl:WidgetProc "root" 1
    frame $top.fra56 \
        -borderwidth 2 -relief groove -background {#808080} -height 215 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 275 
    vTcl:DefineAlias "$top.fra56" "fraRGB" vTcl:WidgetProc "root" 1
    set site_3_0 $top.fra56
    label $site_3_0.cpd58 \
        -activebackground {#83839999b1b1} -activeforeground black \
        -background {#808080} -disabledforeground {#a3a3a3} -font font10 \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify right -text Red 
    vTcl:DefineAlias "$site_3_0.cpd58" "labRed" vTcl:WidgetProc "root" 1
    entry $site_3_0.cpd59 \
        -background {#c1ccd9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font12,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -justify right -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable RGBW_R 
    vTcl:DefineAlias "$site_3_0.cpd59" "entRGBx_R" vTcl:WidgetProc "root" 1
    scale $site_3_0.cpd60 \
        -activebackground {#a4a4a4} -background {#808080} -bigincrement 0.0 \
        -command callback_red(RGB_R) -font TkTextFont -foreground {#000000} \
        -from 0.0 -highlightbackground {#808080} -highlightcolor black \
        -length 140 -orient horizontal -resolution 1.0 -tickinterval 0.0 \
        -to 255.0 -troughcolor {#ff0000} -variable RGB_R 
    vTcl:DefineAlias "$site_3_0.cpd60" "sclRed" vTcl:WidgetProc "root" 1
    label $site_3_0.cpd61 \
        -activebackground {#83839999b1b1} -activeforeground black \
        -background {#808080} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify right -text Green 
    vTcl:DefineAlias "$site_3_0.cpd61" "labGreen" vTcl:WidgetProc "root" 1
    entry $site_3_0.cpd62 \
        -background {#c1ccd9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font12,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -justify right -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable RGBW_G 
    vTcl:DefineAlias "$site_3_0.cpd62" "entRGBx_G" vTcl:WidgetProc "root" 1
    scale $site_3_0.cpd63 \
        -activebackground {#a4a4a4} -background {#808080} -bigincrement 0.0 \
        -command callback_green(RGB_G) -font TkTextFont -foreground {#000000} \
        -from 0.0 -highlightbackground {#808080} -highlightcolor black \
        -length 140 -orient horizontal -resolution 1.0 -tickinterval 0.0 \
        -to 255.0 -troughcolor {#008000} -variable RGB_G 
    vTcl:DefineAlias "$site_3_0.cpd63" "sclGreen" vTcl:WidgetProc "root" 1
    label $site_3_0.cpd64 \
        -activebackground {#83839999b1b1} -activeforeground black \
        -background {#808080} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify right -text Blue 
    vTcl:DefineAlias "$site_3_0.cpd64" "labBlue" vTcl:WidgetProc "root" 1
    entry $site_3_0.cpd65 \
        -background {#c1ccd9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font12,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -justify right -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable RGBW_B 
    vTcl:DefineAlias "$site_3_0.cpd65" "entRGBx_B" vTcl:WidgetProc "root" 1
    scale $site_3_0.cpd66 \
        -activebackground {#a4a4a4} -background {#808080} -bigincrement 0.0 \
        -command callback_blue(RGB_B) -font TkTextFont -foreground {#000000} \
        -from 0.0 -highlightbackground {#808080} -highlightcolor black \
        -length 140 -orient horizontal -resolution 1.0 -tickinterval 0.0 \
        -to 255.0 -troughcolor {#0000ff} -variable RGB_B 
    vTcl:DefineAlias "$site_3_0.cpd66" "sclBlue" vTcl:WidgetProc "root" 1
    entry $site_3_0.cpd39 \
        -background {#c1ccd9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font12,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable RGB_R 
    vTcl:DefineAlias "$site_3_0.cpd39" "entRGB_R" vTcl:WidgetProc "root" 1
    scale $site_3_0.cpd40 \
        -activebackground {#a4a4a4} -background {#808080} -bigincrement 0.0 \
        -command callback_white(RGBW_W) -font TkTextFont \
        -foreground {#000000} -from 0.0 -highlightbackground {#808080} \
        -highlightcolor black -length 140 -orient horizontal -resolution 1.0 \
        -tickinterval 0.0 -to 255.0 -troughcolor {#ffffff} -variable RGBW_W 
    vTcl:DefineAlias "$site_3_0.cpd40" "sclWhite" vTcl:WidgetProc "root" 1
    entry $site_3_0.cpd41 \
        -background {#c1ccd9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font12,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -justify right -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable RGBW_W 
    vTcl:DefineAlias "$site_3_0.cpd41" "entRGBx_W" vTcl:WidgetProc "root" 1
    scale $site_3_0.cpd42 \
        -activebackground {#a4a4a4} -background {#808080} -bigincrement 0.0 \
        -command callback_dim(RGBDim_Dim) -font TkTextFont \
        -foreground {#000000} -from 0.0 -highlightbackground {#808080} \
        -highlightcolor black -length 140 -orient horizontal -resolution 1.0 \
        -tickinterval 0.0 -to 255.0 -troughcolor {#c1ccd9} \
        -variable RGBDim_Dim 
    vTcl:DefineAlias "$site_3_0.cpd42" "sclDim" vTcl:WidgetProc "root" 1
    entry $site_3_0.cpd43 \
        -background {#c1ccd9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font12,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -justify right -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable RGBDim_Dim 
    vTcl:DefineAlias "$site_3_0.cpd43" "entRGBx_Dim" vTcl:WidgetProc "root" 1
    checkbutton $site_3_0.cpd45 \
        -activebackground {#808080} -activeforeground {#000000} -anchor w \
        -background {#808080} -disabledforeground {#c0c0c0} \
        -foreground {#000000} -highlightbackground {#808080} \
        -highlightcolor black -justify left -text Dim -variable RGB_useDim 
    vTcl:DefineAlias "$site_3_0.cpd45" "chkDim" vTcl:WidgetProc "root" 1
    entry $site_3_0.cpd46 \
        -background {#c1ccd9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font12,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable RGB_G 
    vTcl:DefineAlias "$site_3_0.cpd46" "entRGB_G" vTcl:WidgetProc "root" 1
    entry $site_3_0.cpd47 \
        -background {#c1ccd9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font12,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable RGB_B 
    vTcl:DefineAlias "$site_3_0.cpd47" "entRGB_B" vTcl:WidgetProc "root" 1
    place $site_3_0.cpd58 \
        -in $site_3_0 -x 2 -y 18 -width 46 -height 19 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd59 \
        -in $site_3_0 -x 82 -y 12 -width 32 -height 29 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd60 \
        -in $site_3_0 -x 122 -y 4 -anchor nw -bordermode inside 
    place $site_3_0.cpd61 \
        -in $site_3_0 -x 2 -y 58 -width 46 -height 19 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd62 \
        -in $site_3_0 -x 82 -y 52 -width 32 -height 29 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd63 \
        -in $site_3_0 -x 122 -y 44 -anchor nw -bordermode inside 
    place $site_3_0.cpd64 \
        -in $site_3_0 -x 2 -y 98 -width 46 -height 19 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd65 \
        -in $site_3_0 -x 82 -y 92 -width 32 -height 29 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd66 \
        -in $site_3_0 -x 122 -y 84 -anchor nw -bordermode inside 
    place $site_3_0.cpd39 \
        -in $site_3_0 -x 50 -y 12 -width 32 -height 29 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd40 \
        -in $site_3_0 -x 122 -y 124 -anchor nw -bordermode inside 
    place $site_3_0.cpd41 \
        -in $site_3_0 -x 82 -y 132 -width 32 -height 29 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd42 \
        -in $site_3_0 -x 122 -y 164 -anchor nw -bordermode inside 
    place $site_3_0.cpd43 \
        -in $site_3_0 -x 82 -y 172 -width 32 -height 29 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd45 \
        -in $site_3_0 -x 8 -y 178 -anchor nw -bordermode inside 
    place $site_3_0.cpd46 \
        -in $site_3_0 -x 50 -y 52 -width 32 -height 29 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd47 \
        -in $site_3_0 -x 50 -y 92 -width 32 -height 29 -anchor nw \
        -bordermode inside 
    frame $top.cpd39 \
        -borderwidth 2 -relief groove -background {#808080} -height 95 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 135 
    vTcl:DefineAlias "$top.cpd39" "fraXYZ" vTcl:WidgetProc "root" 1
    set site_3_0 $top.cpd39
    label $site_3_0.cpd58 \
        -activebackground {#83839999b1b1} -activeforeground black \
        -background {#808080} -disabledforeground {#a3a3a3} -font font10 \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify right -text X 
    vTcl:DefineAlias "$site_3_0.cpd58" "labXYZ_X" vTcl:WidgetProc "root" 1
    entry $site_3_0.cpd59 \
        -background {#c1ccd9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font11,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable XYZ_X 
    vTcl:DefineAlias "$site_3_0.cpd59" "entXYZ_X" vTcl:WidgetProc "root" 1
    label $site_3_0.cpd61 \
        -activebackground {#83839999b1b1} -activeforeground black \
        -background {#808080} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify right -text Y 
    vTcl:DefineAlias "$site_3_0.cpd61" "labXYZ_Y" vTcl:WidgetProc "root" 1
    entry $site_3_0.cpd62 \
        -background {#c1ccd9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font11,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable XYZ_Y 
    vTcl:DefineAlias "$site_3_0.cpd62" "entXYZ_Y" vTcl:WidgetProc "root" 1
    label $site_3_0.cpd64 \
        -activebackground {#83839999b1b1} -activeforeground black \
        -background {#808080} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify right -text Z 
    vTcl:DefineAlias "$site_3_0.cpd64" "labXYZ_Z" vTcl:WidgetProc "root" 1
    entry $site_3_0.cpd65 \
        -background {#c1ccd9} -disabledbackground {#f0f0f0f0f0f0} \
        -disabledforeground {#a3a3a3} -font $::vTcl(fonts,vTcl:font11,object) \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable XYZ_Z 
    vTcl:DefineAlias "$site_3_0.cpd65" "entXYZ_Z" vTcl:WidgetProc "root" 1
    place $site_3_0.cpd58 \
        -in $site_3_0 -x 2 -y 5 -width 26 -height 19 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd59 \
        -in $site_3_0 -x 30 -y 5 -width 95 -height 20 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd61 \
        -in $site_3_0 -x 2 -y 35 -width 26 -height 19 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd62 \
        -in $site_3_0 -x 30 -y 35 -width 95 -height 20 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd64 \
        -in $site_3_0 -x 2 -y 65 -width 26 -height 19 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd65 \
        -in $site_3_0 -x 30 -y 65 -width 95 -height 20 -anchor nw \
        -bordermode inside 
    frame $top.cpd40 \
        -borderwidth 2 -relief groove -background {#808080} -height 95 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 135 
    vTcl:DefineAlias "$top.cpd40" "fraYxy" vTcl:WidgetProc "root" 1
    set site_3_0 $top.cpd40
    label $site_3_0.cpd58 \
        -activebackground {#83839999b1b1} -activeforeground black \
        -background {#808080} -disabledforeground {#a3a3a3} -font font10 \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify right -text Y 
    vTcl:DefineAlias "$site_3_0.cpd58" "labYxy_Y" vTcl:WidgetProc "root" 1
    entry $site_3_0.cpd59 \
        -background {#c1ccd9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font11,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable Yxy_Y 
    vTcl:DefineAlias "$site_3_0.cpd59" "entYxy_Y" vTcl:WidgetProc "root" 1
    label $site_3_0.cpd61 \
        -activebackground {#83839999b1b1} -activeforeground black \
        -background {#808080} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify right -text x 
    vTcl:DefineAlias "$site_3_0.cpd61" "labYxy_x" vTcl:WidgetProc "root" 1
    entry $site_3_0.cpd62 \
        -background {#c1ccd9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font11,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable Yxy_x 
    vTcl:DefineAlias "$site_3_0.cpd62" "entYxy_x" vTcl:WidgetProc "root" 1
    label $site_3_0.cpd64 \
        -activebackground {#83839999b1b1} -activeforeground black \
        -background {#808080} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify right -text y 
    vTcl:DefineAlias "$site_3_0.cpd64" "labYxy_y" vTcl:WidgetProc "root" 1
    entry $site_3_0.cpd65 \
        -background {#c1ccd9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font11,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable Yxy_y 
    vTcl:DefineAlias "$site_3_0.cpd65" "entYxy_y" vTcl:WidgetProc "root" 1
    place $site_3_0.cpd58 \
        -in $site_3_0 -x 2 -y 5 -width 26 -height 19 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd59 \
        -in $site_3_0 -x 30 -y 5 -width 95 -height 20 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd61 \
        -in $site_3_0 -x 2 -y 35 -width 26 -height 19 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd62 \
        -in $site_3_0 -x 30 -y 35 -width 95 -height 20 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd64 \
        -in $site_3_0 -x 2 -y 65 -width 26 -height 19 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd65 \
        -in $site_3_0 -x 30 -y 65 -width 95 -height 20 -anchor nw \
        -bordermode inside 
    frame $top.cpd41 \
        -borderwidth 2 -relief groove -background {#808080} -height 95 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 105 
    vTcl:DefineAlias "$top.cpd41" "fraHSV" vTcl:WidgetProc "root" 1
    set site_3_0 $top.cpd41
    label $site_3_0.cpd58 \
        -activebackground {#83839999b1b1} -activeforeground black \
        -background {#808080} -disabledforeground {#a3a3a3} -font font10 \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify right -text H 
    vTcl:DefineAlias "$site_3_0.cpd58" "labHSV_H" vTcl:WidgetProc "root" 1
    entry $site_3_0.cpd59 \
        -background {#c1ccd9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font11,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable HSV_H 
    vTcl:DefineAlias "$site_3_0.cpd59" "entHSV_H" vTcl:WidgetProc "root" 1
    label $site_3_0.cpd61 \
        -activebackground {#83839999b1b1} -activeforeground black \
        -background {#808080} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify right -text S 
    vTcl:DefineAlias "$site_3_0.cpd61" "labHSV_S" vTcl:WidgetProc "root" 1
    entry $site_3_0.cpd62 \
        -background {#c1ccd9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font11,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable HSV_S 
    vTcl:DefineAlias "$site_3_0.cpd62" "entHSV_S" vTcl:WidgetProc "root" 1
    label $site_3_0.cpd64 \
        -activebackground {#83839999b1b1} -activeforeground black \
        -background {#808080} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify right -text V 
    vTcl:DefineAlias "$site_3_0.cpd64" "labHSV_V" vTcl:WidgetProc "root" 1
    entry $site_3_0.cpd65 \
        -background {#c1ccd9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font11,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable HSV_V 
    vTcl:DefineAlias "$site_3_0.cpd65" "entHSV_V" vTcl:WidgetProc "root" 1
    place $site_3_0.cpd58 \
        -in $site_3_0 -x 2 -y 5 -width 26 -height 19 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd59 \
        -in $site_3_0 -x 30 -y 5 -width 64 -height 20 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd61 \
        -in $site_3_0 -x 2 -y 35 -width 26 -height 19 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd62 \
        -in $site_3_0 -x 30 -y 35 -width 64 -height 20 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd64 \
        -in $site_3_0 -x 2 -y 65 -width 26 -height 19 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd65 \
        -in $site_3_0 -x 30 -y 65 -width 64 -height 20 -anchor nw \
        -bordermode inside 
    frame $top.cpd42 \
        -borderwidth 2 -relief groove -background {#808080} -height 95 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 105 
    vTcl:DefineAlias "$top.cpd42" "fraHSL" vTcl:WidgetProc "root" 1
    set site_3_0 $top.cpd42
    label $site_3_0.cpd58 \
        -activebackground {#83839999b1b1} -activeforeground black \
        -background {#808080} -disabledforeground {#a3a3a3} -font font10 \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify right -text H 
    vTcl:DefineAlias "$site_3_0.cpd58" "labHSL_H" vTcl:WidgetProc "root" 1
    entry $site_3_0.cpd59 \
        -background {#c1ccd9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font11,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable HSL_H 
    vTcl:DefineAlias "$site_3_0.cpd59" "entHSL_H" vTcl:WidgetProc "root" 1
    label $site_3_0.cpd61 \
        -activebackground {#83839999b1b1} -activeforeground black \
        -background {#808080} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify right -text S 
    vTcl:DefineAlias "$site_3_0.cpd61" "labHSL_S" vTcl:WidgetProc "root" 1
    entry $site_3_0.cpd62 \
        -background {#c1ccd9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font11,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable HSL_S 
    vTcl:DefineAlias "$site_3_0.cpd62" "entHSL_S" vTcl:WidgetProc "root" 1
    label $site_3_0.cpd64 \
        -activebackground {#83839999b1b1} -activeforeground black \
        -background {#808080} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify right -text L 
    vTcl:DefineAlias "$site_3_0.cpd64" "labHSL_L" vTcl:WidgetProc "root" 1
    entry $site_3_0.cpd65 \
        -background {#c1ccd9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font11,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable HSL_L 
    vTcl:DefineAlias "$site_3_0.cpd65" "entHSL_L" vTcl:WidgetProc "root" 1
    place $site_3_0.cpd58 \
        -in $site_3_0 -x 2 -y 5 -width 26 -height 19 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd59 \
        -in $site_3_0 -x 30 -y 5 -width 64 -height 20 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd61 \
        -in $site_3_0 -x 2 -y 35 -width 26 -height 19 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd62 \
        -in $site_3_0 -x 30 -y 35 -width 64 -height 20 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd64 \
        -in $site_3_0 -x 2 -y 65 -width 26 -height 19 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd65 \
        -in $site_3_0 -x 30 -y 65 -width 64 -height 20 -anchor nw \
        -bordermode inside 
    frame $top.cpd43 \
        -borderwidth 2 -relief groove -background {#808080} -height 95 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 135 
    vTcl:DefineAlias "$top.cpd43" "fraCIELuv" vTcl:WidgetProc "root" 1
    set site_3_0 $top.cpd43
    label $site_3_0.cpd58 \
        -activebackground {#83839999b1b1} -activeforeground black \
        -background {#808080} -disabledforeground {#a3a3a3} -font font10 \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify right -text L* 
    vTcl:DefineAlias "$site_3_0.cpd58" "labLuv_L" vTcl:WidgetProc "root" 1
    entry $site_3_0.cpd59 \
        -background {#c1ccd9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font11,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable CLuv_L 
    vTcl:DefineAlias "$site_3_0.cpd59" "entLuv_L" vTcl:WidgetProc "root" 1
    label $site_3_0.cpd61 \
        -activebackground {#83839999b1b1} -activeforeground black \
        -background {#808080} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify right -text u 
    vTcl:DefineAlias "$site_3_0.cpd61" "labLuv_u" vTcl:WidgetProc "root" 1
    entry $site_3_0.cpd62 \
        -background {#c1ccd9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font11,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable CLuv_u 
    vTcl:DefineAlias "$site_3_0.cpd62" "entLuv_u" vTcl:WidgetProc "root" 1
    label $site_3_0.cpd64 \
        -activebackground {#83839999b1b1} -activeforeground black \
        -background {#808080} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify right -text v 
    vTcl:DefineAlias "$site_3_0.cpd64" "labLuv_v" vTcl:WidgetProc "root" 1
    entry $site_3_0.cpd65 \
        -background {#c1ccd9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font11,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable CLuv_v 
    vTcl:DefineAlias "$site_3_0.cpd65" "entLuv_v" vTcl:WidgetProc "root" 1
    place $site_3_0.cpd58 \
        -in $site_3_0 -x 2 -y 5 -width 26 -height 19 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd59 \
        -in $site_3_0 -x 30 -y 5 -width 95 -height 20 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd61 \
        -in $site_3_0 -x 2 -y 35 -width 26 -height 19 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd62 \
        -in $site_3_0 -x 30 -y 35 -width 95 -height 20 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd64 \
        -in $site_3_0 -x 2 -y 65 -width 26 -height 19 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd65 \
        -in $site_3_0 -x 30 -y 65 -width 95 -height 20 -anchor nw \
        -bordermode inside 
    frame $top.cpd44 \
        -borderwidth 2 -relief groove -background {#808080} -height 95 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 135 
    vTcl:DefineAlias "$top.cpd44" "fraCIELCHab" vTcl:WidgetProc "root" 1
    set site_3_0 $top.cpd44
    label $site_3_0.cpd58 \
        -activebackground {#83839999b1b1} -activeforeground black \
        -background {#808080} -disabledforeground {#a3a3a3} -font font10 \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify right -text L* 
    vTcl:DefineAlias "$site_3_0.cpd58" "labLCHab_L" vTcl:WidgetProc "root" 1
    entry $site_3_0.cpd59 \
        -background {#c1ccd9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font11,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable CLCHab_L 
    vTcl:DefineAlias "$site_3_0.cpd59" "entLCHab_L" vTcl:WidgetProc "root" 1
    label $site_3_0.cpd61 \
        -activebackground {#83839999b1b1} -activeforeground black \
        -background {#808080} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify right -text C 
    vTcl:DefineAlias "$site_3_0.cpd61" "labLCHab_C" vTcl:WidgetProc "root" 1
    entry $site_3_0.cpd62 \
        -background {#c1ccd9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font11,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable CLCHab_C 
    vTcl:DefineAlias "$site_3_0.cpd62" "entLCHab_C" vTcl:WidgetProc "root" 1
    label $site_3_0.cpd64 \
        -activebackground {#83839999b1b1} -activeforeground black \
        -background {#808080} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify right -text H° 
    vTcl:DefineAlias "$site_3_0.cpd64" "labLCHab_H" vTcl:WidgetProc "root" 1
    entry $site_3_0.cpd65 \
        -background {#c1ccd9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font11,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable CLCHab_H 
    vTcl:DefineAlias "$site_3_0.cpd65" "entLCHab_H" vTcl:WidgetProc "root" 1
    place $site_3_0.cpd58 \
        -in $site_3_0 -x 2 -y 5 -width 26 -height 19 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd59 \
        -in $site_3_0 -x 30 -y 5 -width 95 -height 20 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd61 \
        -in $site_3_0 -x 2 -y 35 -width 26 -height 19 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd62 \
        -in $site_3_0 -x 30 -y 35 -width 95 -height 20 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd64 \
        -in $site_3_0 -x 2 -y 65 -width 26 -height 19 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd65 \
        -in $site_3_0 -x 30 -y 65 -width 95 -height 20 -anchor nw \
        -bordermode inside 
    frame $top.cpd45 \
        -borderwidth 2 -relief groove -background {#808080} -height 95 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 135 
    vTcl:DefineAlias "$top.cpd45" "fraHunterLab" vTcl:WidgetProc "root" 1
    set site_3_0 $top.cpd45
    label $site_3_0.cpd58 \
        -activebackground {#83839999b1b1} -activeforeground black \
        -background {#808080} -disabledforeground {#a3a3a3} -font font10 \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify right -text HL* 
    vTcl:DefineAlias "$site_3_0.cpd58" "labHLab_L" vTcl:WidgetProc "root" 1
    entry $site_3_0.cpd59 \
        -background {#c1ccd9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font11,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable HLab_L 
    vTcl:DefineAlias "$site_3_0.cpd59" "entHLab_L" vTcl:WidgetProc "root" 1
    label $site_3_0.cpd61 \
        -activebackground {#83839999b1b1} -activeforeground black \
        -background {#808080} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify right -text Ha 
    vTcl:DefineAlias "$site_3_0.cpd61" "labHLab_a" vTcl:WidgetProc "root" 1
    entry $site_3_0.cpd62 \
        -background {#c1ccd9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font11,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable HLab_a 
    vTcl:DefineAlias "$site_3_0.cpd62" "entHLab_a" vTcl:WidgetProc "root" 1
    label $site_3_0.cpd64 \
        -activebackground {#83839999b1b1} -activeforeground black \
        -background {#808080} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify right -text Hb 
    vTcl:DefineAlias "$site_3_0.cpd64" "labHLab_b" vTcl:WidgetProc "root" 1
    entry $site_3_0.cpd65 \
        -background {#c1ccd9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font11,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable HLab_b 
    vTcl:DefineAlias "$site_3_0.cpd65" "entHLab_b" vTcl:WidgetProc "root" 1
    place $site_3_0.cpd58 \
        -in $site_3_0 -x 2 -y 5 -width 26 -height 19 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd59 \
        -in $site_3_0 -x 30 -y 5 -width 95 -height 20 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd61 \
        -in $site_3_0 -x 2 -y 35 -width 26 -height 19 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd62 \
        -in $site_3_0 -x 30 -y 35 -width 95 -height 20 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd64 \
        -in $site_3_0 -x 2 -y 65 -width 26 -height 19 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd65 \
        -in $site_3_0 -x 30 -y 65 -width 95 -height 20 -anchor nw \
        -bordermode inside 
    frame $top.cpd46 \
        -borderwidth 2 -relief groove -background {#808080} -height 95 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 135 
    vTcl:DefineAlias "$top.cpd46" "fraCIELab" vTcl:WidgetProc "root" 1
    set site_3_0 $top.cpd46
    label $site_3_0.cpd58 \
        -activebackground {#83839999b1b1} -activeforeground black \
        -background {#808080} -disabledforeground {#a3a3a3} -font font10 \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify right -text CL* 
    vTcl:DefineAlias "$site_3_0.cpd58" "labCLab_L" vTcl:WidgetProc "root" 1
    entry $site_3_0.cpd59 \
        -background {#c1ccd9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font11,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable CLab_L 
    vTcl:DefineAlias "$site_3_0.cpd59" "entCLab_L" vTcl:WidgetProc "root" 1
    label $site_3_0.cpd61 \
        -activebackground {#83839999b1b1} -activeforeground black \
        -background {#808080} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify right -text Ca 
    vTcl:DefineAlias "$site_3_0.cpd61" "labCLab_a" vTcl:WidgetProc "root" 1
    entry $site_3_0.cpd62 \
        -background {#c1ccd9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font11,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable CLab_a 
    vTcl:DefineAlias "$site_3_0.cpd62" "entCLab_a" vTcl:WidgetProc "root" 1
    label $site_3_0.cpd64 \
        -activebackground {#83839999b1b1} -activeforeground black \
        -background {#808080} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify right -text Cb 
    vTcl:DefineAlias "$site_3_0.cpd64" "labCLab_b" vTcl:WidgetProc "root" 1
    entry $site_3_0.cpd65 \
        -background {#c1ccd9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font11,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable CLab_b 
    vTcl:DefineAlias "$site_3_0.cpd65" "entCLab_b" vTcl:WidgetProc "root" 1
    place $site_3_0.cpd58 \
        -in $site_3_0 -x 2 -y 5 -width 26 -height 19 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd59 \
        -in $site_3_0 -x 30 -y 5 -width 95 -height 20 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd61 \
        -in $site_3_0 -x 2 -y 35 -width 26 -height 19 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd62 \
        -in $site_3_0 -x 30 -y 35 -width 95 -height 20 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd64 \
        -in $site_3_0 -x 2 -y 65 -width 26 -height 19 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd65 \
        -in $site_3_0 -x 30 -y 65 -width 95 -height 20 -anchor nw \
        -bordermode inside 
    frame $top.cpd47 \
        -borderwidth 2 -relief groove -background {#808080} -height 95 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 105 
    vTcl:DefineAlias "$top.cpd47" "fraCMY" vTcl:WidgetProc "root" 1
    set site_3_0 $top.cpd47
    label $site_3_0.cpd58 \
        -activebackground {#83839999b1b1} -activeforeground black \
        -background {#808080} -disabledforeground {#a3a3a3} -font font10 \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify right -text C 
    vTcl:DefineAlias "$site_3_0.cpd58" "labCMY_C" vTcl:WidgetProc "root" 1
    entry $site_3_0.cpd59 \
        -background {#c1ccd9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font11,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable CMY_C 
    vTcl:DefineAlias "$site_3_0.cpd59" "entCMY_C" vTcl:WidgetProc "root" 1
    label $site_3_0.cpd61 \
        -activebackground {#83839999b1b1} -activeforeground black \
        -background {#808080} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify right -text M 
    vTcl:DefineAlias "$site_3_0.cpd61" "labCMY_M" vTcl:WidgetProc "root" 1
    entry $site_3_0.cpd62 \
        -background {#c1ccd9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font11,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable CMY_M 
    vTcl:DefineAlias "$site_3_0.cpd62" "entCMY_M" vTcl:WidgetProc "root" 1
    label $site_3_0.cpd64 \
        -activebackground {#83839999b1b1} -activeforeground black \
        -background {#808080} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify right -text Y 
    vTcl:DefineAlias "$site_3_0.cpd64" "labCMY_Y" vTcl:WidgetProc "root" 1
    entry $site_3_0.cpd65 \
        -background {#c1ccd9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font11,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable CMY_Y 
    vTcl:DefineAlias "$site_3_0.cpd65" "entCMY_Y" vTcl:WidgetProc "root" 1
    place $site_3_0.cpd58 \
        -in $site_3_0 -x 2 -y 5 -width 26 -height 19 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd59 \
        -in $site_3_0 -x 30 -y 5 -width 64 -height 20 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd61 \
        -in $site_3_0 -x 2 -y 35 -width 26 -height 19 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd62 \
        -in $site_3_0 -x 30 -y 35 -width 64 -height 20 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd64 \
        -in $site_3_0 -x 2 -y 65 -width 26 -height 19 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd65 \
        -in $site_3_0 -x 30 -y 65 -width 64 -height 20 -anchor nw \
        -bordermode inside 
    frame $top.cpd48 \
        -borderwidth 2 -relief groove -background {#808080} -height 125 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 105 
    vTcl:DefineAlias "$top.cpd48" "fraCMYK" vTcl:WidgetProc "root" 1
    set site_3_0 $top.cpd48
    label $site_3_0.cpd58 \
        -activebackground {#83839999b1b1} -activeforeground black \
        -background {#808080} -disabledforeground {#a3a3a3} -font font10 \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify right -text C 
    vTcl:DefineAlias "$site_3_0.cpd58" "labCMYK_C" vTcl:WidgetProc "root" 1
    entry $site_3_0.cpd59 \
        -background {#c1ccd9} -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable CMYK_C 
    vTcl:DefineAlias "$site_3_0.cpd59" "entCMYK_C" vTcl:WidgetProc "root" 1
    label $site_3_0.cpd61 \
        -activebackground {#83839999b1b1} -activeforeground black \
        -background {#808080} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify right -text M 
    vTcl:DefineAlias "$site_3_0.cpd61" "labCMYK_M" vTcl:WidgetProc "root" 1
    entry $site_3_0.cpd62 \
        -background {#c1ccd9} -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable CMYK_M 
    vTcl:DefineAlias "$site_3_0.cpd62" "entCMYK_M" vTcl:WidgetProc "root" 1
    label $site_3_0.cpd64 \
        -activebackground {#83839999b1b1} -activeforeground black \
        -background {#808080} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify right -text Y 
    vTcl:DefineAlias "$site_3_0.cpd64" "labCMYK_Y" vTcl:WidgetProc "root" 1
    entry $site_3_0.cpd65 \
        -background {#c1ccd9} -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable CMYK_Y 
    vTcl:DefineAlias "$site_3_0.cpd65" "entCMYK_Y" vTcl:WidgetProc "root" 1
    entry $site_3_0.cpd49 \
        -background {#c1ccd9} -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable CMYK_K 
    vTcl:DefineAlias "$site_3_0.cpd49" "entCMYK_K" vTcl:WidgetProc "root" 1
    label $site_3_0.cpd50 \
        -activebackground {#83839999b1b1} -activeforeground black \
        -background {#808080} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify right -text K 
    vTcl:DefineAlias "$site_3_0.cpd50" "labCMYK_K" vTcl:WidgetProc "root" 1
    place $site_3_0.cpd58 \
        -in $site_3_0 -x 2 -y 5 -width 26 -height 19 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd59 \
        -in $site_3_0 -x 30 -y 5 -width 64 -height 20 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd61 \
        -in $site_3_0 -x 2 -y 35 -width 26 -height 19 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd62 \
        -in $site_3_0 -x 30 -y 35 -width 64 -height 20 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd64 \
        -in $site_3_0 -x 2 -y 65 -width 26 -height 19 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd65 \
        -in $site_3_0 -x 30 -y 65 -width 64 -height 20 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd49 \
        -in $site_3_0 -x 30 -y 95 -width 64 -height 20 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd50 \
        -in $site_3_0 -x 2 -y 95 -width 26 -height 19 -anchor nw \
        -bordermode inside 
    frame $top.cpd52 \
        -borderwidth 2 -relief groove -background {#808080} -height 95 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 165 
    vTcl:DefineAlias "$top.cpd52" "fraWEB" vTcl:WidgetProc "root" 1
    set site_3_0 $top.cpd52
    label $site_3_0.cpd58 \
        -activebackground {#83839999b1b1} -activeforeground black \
        -background {#808080} -disabledforeground {#a3a3a3} -font font10 \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify right -text HTML 
    vTcl:DefineAlias "$site_3_0.cpd58" "labHTML" vTcl:WidgetProc "root" 1
    entry $site_3_0.cpd59 \
        -background {#c1ccd9} -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable colHTML 
    vTcl:DefineAlias "$site_3_0.cpd59" "entHTML" vTcl:WidgetProc "root" 1
    label $site_3_0.cpd61 \
        -activebackground {#83839999b1b1} -activeforeground black \
        -background {#808080} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify right -text CSS 
    vTcl:DefineAlias "$site_3_0.cpd61" "labCSS" vTcl:WidgetProc "root" 1
    entry $site_3_0.cpd62 \
        -background {#c1ccd9} -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable colCSS 
    vTcl:DefineAlias "$site_3_0.cpd62" "entCSS" vTcl:WidgetProc "root" 1
    label $site_3_0.cpd64 \
        -activebackground {#83839999b1b1} -activeforeground black \
        -background {#808080} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify right -text WebSafe 
    vTcl:DefineAlias "$site_3_0.cpd64" "labWebSafe" vTcl:WidgetProc "root" 1
    entry $site_3_0.cpd65 \
        -background {#c1ccd9} -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable colWebSafe 
    vTcl:DefineAlias "$site_3_0.cpd65" "entWebSafe" vTcl:WidgetProc "root" 1
    place $site_3_0.cpd58 \
        -in $site_3_0 -x 2 -y 5 -width 56 -height 19 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd59 \
        -in $site_3_0 -x 60 -y 5 -width 95 -height 20 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd61 \
        -in $site_3_0 -x 2 -y 35 -width 56 -height 19 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd62 \
        -in $site_3_0 -x 60 -y 35 -width 95 -height 20 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd64 \
        -in $site_3_0 -x 2 -y 65 -width 56 -height 19 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd65 \
        -in $site_3_0 -x 60 -y 65 -width 95 -height 20 -anchor nw \
        -bordermode inside 
    button $top.but37 \
        -activebackground {#c0c0c0} -activeforeground {#000000} \
        -background {#808080} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#808080} \
        -highlightcolor black -overrelief raised -pady 0 -text {Color Wheel} 
    vTcl:DefineAlias "$top.but37" "butColorWheel" vTcl:WidgetProc "root" 1
    frame $top.cpd51 \
        -borderwidth 2 -background {#808080} -height 385 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 95 
    vTcl:DefineAlias "$top.cpd51" "fraFrom" vTcl:WidgetProc "root" 1
    set site_3_0 $top.cpd51
    label $site_3_0.lab55 \
        -activebackground {#f9f9f9} -activeforeground black -anchor w \
        -background {#808080} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text From: 
    vTcl:DefineAlias "$site_3_0.lab55" "Label1" vTcl:WidgetProc "root" 1
    radiobutton $site_3_0.rad56 \
        -activebackground {#f9f9f9} -activeforeground {#000000} -anchor w \
        -background {#808080} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#808080} \
        -highlightcolor black -justify left -text RGB -value 0 
    vTcl:DefineAlias "$site_3_0.rad56" "radRGB" vTcl:WidgetProc "root" 1
    radiobutton $site_3_0.cpd57 \
        -activebackground {#f9f9f9} -activeforeground {#000000} -anchor w \
        -background {#808080} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#808080} \
        -highlightcolor black -justify left -text HSV -value 1 
    vTcl:DefineAlias "$site_3_0.cpd57" "radHSV" vTcl:WidgetProc "root" 1
    radiobutton $site_3_0.cpd58 \
        -activebackground {#f9f9f9} -activeforeground {#000000} -anchor w \
        -background {#808080} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#808080} \
        -highlightcolor black -justify left -text HSL -value 2 
    vTcl:DefineAlias "$site_3_0.cpd58" "radHSL" vTcl:WidgetProc "root" 1
    radiobutton $site_3_0.cpd59 \
        -activebackground {#f9f9f9} -activeforeground {#000000} -anchor w \
        -background {#808080} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#808080} \
        -highlightcolor black -justify left -text XYZ -value 3 
    vTcl:DefineAlias "$site_3_0.cpd59" "radXYZ" vTcl:WidgetProc "root" 1
    radiobutton $site_3_0.cpd60 \
        -activebackground {#f9f9f9} -activeforeground {#000000} -anchor w \
        -background {#808080} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#808080} \
        -highlightcolor black -justify left -text Yxy -value 4 
    vTcl:DefineAlias "$site_3_0.cpd60" "radYxy" vTcl:WidgetProc "root" 1
    radiobutton $site_3_0.cpd61 \
        -activebackground {#f9f9f9} -activeforeground {#000000} -anchor w \
        -background {#808080} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#808080} \
        -highlightcolor black -justify left -text {Hunter Lab} -value 5 
    vTcl:DefineAlias "$site_3_0.cpd61" "radHLab" vTcl:WidgetProc "root" 1
    radiobutton $site_3_0.cpd62 \
        -activebackground {#f9f9f9} -activeforeground {#000000} -anchor w \
        -background {#808080} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#808080} \
        -highlightcolor black -justify left -text {CIE L*ab} -value 6 
    vTcl:DefineAlias "$site_3_0.cpd62" "radCLab" vTcl:WidgetProc "root" 1
    radiobutton $site_3_0.cpd63 \
        -activebackground {#f9f9f9} -activeforeground {#000000} -anchor w \
        -background {#808080} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#808080} \
        -highlightcolor black -justify left -text {CIE L*uv} -value 7 
    vTcl:DefineAlias "$site_3_0.cpd63" "radCLuv" vTcl:WidgetProc "root" 1
    radiobutton $site_3_0.cpd64 \
        -activebackground {#f9f9f9} -activeforeground {#000000} -anchor w \
        -background {#808080} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#808080} \
        -highlightcolor black -justify left -text {CIE L*CH°ab} -value 8 
    vTcl:DefineAlias "$site_3_0.cpd64" "radCLCHab" vTcl:WidgetProc "root" 1
    radiobutton $site_3_0.cpd65 \
        -activebackground {#f9f9f9} -activeforeground {#000000} -anchor w \
        -background {#808080} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#808080} \
        -highlightcolor black -justify left -text CMY -value 9 
    vTcl:DefineAlias "$site_3_0.cpd65" "radCMY" vTcl:WidgetProc "root" 1
    radiobutton $site_3_0.cpd66 \
        -activebackground {#f9f9f9} -activeforeground {#000000} -anchor w \
        -background {#808080} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#808080} \
        -highlightcolor black -justify left -text CMYK -value 10 
    vTcl:DefineAlias "$site_3_0.cpd66" "radCMYK" vTcl:WidgetProc "root" 1
    radiobutton $site_3_0.cpd67 \
        -activebackground {#f9f9f9} -activeforeground {#000000} -anchor w \
        -background {#808080} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#808080} \
        -highlightcolor black -justify left -text RGBW -value 11 
    vTcl:DefineAlias "$site_3_0.cpd67" "radRGBW" vTcl:WidgetProc "root" 1
    radiobutton $site_3_0.cpd68 \
        -activebackground {#f9f9f9} -activeforeground {#000000} -anchor w \
        -background {#808080} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#808080} \
        -highlightcolor black -justify left -text RGBDim -value 12 
    vTcl:DefineAlias "$site_3_0.cpd68" "radRGBDim" vTcl:WidgetProc "root" 1
    radiobutton $site_3_0.cpd69 \
        -activebackground {#f9f9f9} -activeforeground {#000000} -anchor w \
        -background {#808080} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#808080} \
        -highlightcolor black -justify left -text HTML -value 13 
    vTcl:DefineAlias "$site_3_0.cpd69" "radHTML" vTcl:WidgetProc "root" 1
    radiobutton $site_3_0.cpd70 \
        -activebackground {#f9f9f9} -activeforeground {#000000} -anchor w \
        -background {#808080} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#808080} \
        -highlightcolor black -justify left -text CSS -value 14 
    vTcl:DefineAlias "$site_3_0.cpd70" "radCSS" vTcl:WidgetProc "root" 1
    radiobutton $site_3_0.cpd54 \
        -activebackground {#f9f9f9} -activeforeground {#000000} -anchor w \
        -background {#808080} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#808080} \
        -highlightcolor black -justify left -text YUV -value 15 
    vTcl:DefineAlias "$site_3_0.cpd54" "radYUV" vTcl:WidgetProc "root" 1
    radiobutton $site_3_0.cpd55 \
        -activebackground {#f9f9f9} -activeforeground {#000000} -anchor w \
        -background {#808080} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#808080} \
        -highlightcolor black -justify left -text YCbCr -value 16 
    vTcl:DefineAlias "$site_3_0.cpd55" "radYCbCr" vTcl:WidgetProc "root" 1
    radiobutton $site_3_0.cpd71 \
        -activebackground {#f9f9f9} -activeforeground {#000000} -anchor w \
        -background {#808080} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#808080} \
        -highlightcolor black -justify left -text {CIE L*CH°uv} -value 8 
    vTcl:DefineAlias "$site_3_0.cpd71" "radCLCHuv" vTcl:WidgetProc "root" 1
    place $site_3_0.lab55 \
        -in $site_3_0 -x 10 -y 10 -width 44 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_3_0.rad56 \
        -in $site_3_0 -x 7 -y 32 -anchor nw -bordermode ignore 
    place $site_3_0.cpd57 \
        -in $site_3_0 -x 5 -y 50 -anchor nw -bordermode inside 
    place $site_3_0.cpd58 \
        -in $site_3_0 -x 5 -y 70 -anchor nw -bordermode inside 
    place $site_3_0.cpd59 \
        -in $site_3_0 -x 5 -y 90 -anchor nw -bordermode inside 
    place $site_3_0.cpd60 \
        -in $site_3_0 -x 5 -y 110 -anchor nw -bordermode inside 
    place $site_3_0.cpd61 \
        -in $site_3_0 -x 5 -y 130 -anchor nw -bordermode inside 
    place $site_3_0.cpd62 \
        -in $site_3_0 -x 5 -y 150 -anchor nw -bordermode inside 
    place $site_3_0.cpd63 \
        -in $site_3_0 -x 5 -y 170 -anchor nw -bordermode inside 
    place $site_3_0.cpd64 \
        -in $site_3_0 -x 5 -y 190 -anchor nw -bordermode inside 
    place $site_3_0.cpd65 \
        -in $site_3_0 -x 5 -y 230 -anchor nw -bordermode inside 
    place $site_3_0.cpd66 \
        -in $site_3_0 -x 5 -y 250 -anchor nw -bordermode inside 
    place $site_3_0.cpd67 \
        -in $site_3_0 -x 5 -y 270 -anchor nw -bordermode inside 
    place $site_3_0.cpd68 \
        -in $site_3_0 -x 5 -y 290 -anchor nw -bordermode inside 
    place $site_3_0.cpd69 \
        -in $site_3_0 -x 5 -y 310 -anchor nw -bordermode inside 
    place $site_3_0.cpd70 \
        -in $site_3_0 -x 5 -y 330 -anchor nw -bordermode inside 
    place $site_3_0.cpd54 \
        -in $site_3_0 -x 5 -y 350 -anchor nw -bordermode inside 
    place $site_3_0.cpd55 \
        -in $site_3_0 -x 5 -y 370 -anchor nw -bordermode inside 
    place $site_3_0.cpd71 \
        -in $site_3_0 -x 5 -y 210 -anchor nw -bordermode inside 
    checkbutton $top.cpd37 \
        -activebackground {#808080} -activeforeground {#000000} -anchor w \
        -background {#808080} -disabledforeground {#c0c0c0} \
        -foreground {#000000} -highlightbackground {#808080} \
        -highlightcolor black -justify left -text White -variable RGB_useW 
    vTcl:DefineAlias "$top.cpd37" "chkWhite" vTcl:WidgetProc "root" 1
    checkbutton $top.cpd38 \
        -activebackground {#f9f9f9} -activeforeground {#000000} \
        -background {#808080} -disabledforeground {#c0c0c0} \
        -foreground {#000000} -highlightbackground {#808080} \
        -highlightcolor black -justify left -text {Scale Values} \
        -variable XYZ_scaled 
    vTcl:DefineAlias "$top.cpd38" "chkScaleXYZ1" vTcl:WidgetProc "root" 1
    checkbutton $top.cpd49 \
        -activebackground {#808080} -activeforeground {#000000} \
        -background {#808080} -disabledforeground {#c0c0c0} \
        -foreground {#000000} -highlightbackground {#808080} \
        -highlightcolor black -justify left -text {Adapt Dim} \
        -variable RGBDim_adapt 
    vTcl:DefineAlias "$top.cpd49" "chkAdaptRGBDim1" vTcl:WidgetProc "root" 1
    frame $top.cpd50 \
        -borderwidth 2 -relief groove -background {#808080} -height 95 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 105 
    vTcl:DefineAlias "$top.cpd50" "fraYUV" vTcl:WidgetProc "root" 1
    set site_3_0 $top.cpd50
    label $site_3_0.cpd58 \
        -activebackground {#83839999b1b1} -activeforeground black \
        -background {#808080} -disabledforeground {#a3a3a3} -font font10 \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify right -text Y 
    vTcl:DefineAlias "$site_3_0.cpd58" "labYUV_Y" vTcl:WidgetProc "root" 1
    entry $site_3_0.cpd59 \
        -background {#c1ccd9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font11,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable YUV_Y 
    vTcl:DefineAlias "$site_3_0.cpd59" "entYUV_Y" vTcl:WidgetProc "root" 1
    label $site_3_0.cpd61 \
        -activebackground {#83839999b1b1} -activeforeground black \
        -background {#808080} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify right -text U 
    vTcl:DefineAlias "$site_3_0.cpd61" "labYUV_U" vTcl:WidgetProc "root" 1
    entry $site_3_0.cpd62 \
        -background {#c1ccd9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font11,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable YUV_U 
    vTcl:DefineAlias "$site_3_0.cpd62" "entYUV_U" vTcl:WidgetProc "root" 1
    label $site_3_0.cpd64 \
        -activebackground {#83839999b1b1} -activeforeground black \
        -background {#808080} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify right -text V 
    vTcl:DefineAlias "$site_3_0.cpd64" "labYUV_V" vTcl:WidgetProc "root" 1
    entry $site_3_0.cpd65 \
        -background {#c1ccd9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font11,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable YUV_V 
    vTcl:DefineAlias "$site_3_0.cpd65" "entYUV_V" vTcl:WidgetProc "root" 1
    place $site_3_0.cpd58 \
        -in $site_3_0 -x 2 -y 5 -width 26 -height 19 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd59 \
        -in $site_3_0 -x 30 -y 5 -width 64 -height 20 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd61 \
        -in $site_3_0 -x 2 -y 35 -width 26 -height 19 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd62 \
        -in $site_3_0 -x 30 -y 35 -width 64 -height 20 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd64 \
        -in $site_3_0 -x 2 -y 65 -width 26 -height 19 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd65 \
        -in $site_3_0 -x 30 -y 65 -width 64 -height 20 -anchor nw \
        -bordermode inside 
    frame $top.cpd53 \
        -borderwidth 2 -relief groove -background {#808080} -height 95 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 105 
    vTcl:DefineAlias "$top.cpd53" "fraYCbCr" vTcl:WidgetProc "root" 1
    set site_3_0 $top.cpd53
    label $site_3_0.cpd58 \
        -activebackground {#83839999b1b1} -activeforeground black \
        -background {#808080} -disabledforeground {#a3a3a3} -font font10 \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify right -text Y 
    vTcl:DefineAlias "$site_3_0.cpd58" "labYCbCr_Y" vTcl:WidgetProc "root" 1
    entry $site_3_0.cpd59 \
        -background {#c1ccd9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font11,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable YCbCr_Y 
    vTcl:DefineAlias "$site_3_0.cpd59" "entYCbCr_Y" vTcl:WidgetProc "root" 1
    label $site_3_0.cpd61 \
        -activebackground {#83839999b1b1} -activeforeground black \
        -background {#808080} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify right -text Cb 
    vTcl:DefineAlias "$site_3_0.cpd61" "labYCbCr_Cb" vTcl:WidgetProc "root" 1
    entry $site_3_0.cpd62 \
        -background {#c1ccd9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font11,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable YCbCr_Cb 
    vTcl:DefineAlias "$site_3_0.cpd62" "entYCbCr_Cb" vTcl:WidgetProc "root" 1
    label $site_3_0.cpd64 \
        -activebackground {#83839999b1b1} -activeforeground black \
        -background {#808080} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify right -text Cr 
    vTcl:DefineAlias "$site_3_0.cpd64" "labYCbCr_Cr" vTcl:WidgetProc "root" 1
    entry $site_3_0.cpd65 \
        -background {#c1ccd9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font11,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable YCbCr_Cr 
    vTcl:DefineAlias "$site_3_0.cpd65" "entYCbCr_Cr" vTcl:WidgetProc "root" 1
    place $site_3_0.cpd58 \
        -in $site_3_0 -x 2 -y 5 -width 26 -height 19 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd59 \
        -in $site_3_0 -x 30 -y 5 -width 64 -height 20 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd61 \
        -in $site_3_0 -x 2 -y 35 -width 26 -height 19 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd62 \
        -in $site_3_0 -x 30 -y 35 -width 64 -height 20 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd64 \
        -in $site_3_0 -x 2 -y 65 -width 26 -height 19 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd65 \
        -in $site_3_0 -x 30 -y 65 -width 64 -height 20 -anchor nw \
        -bordermode inside 
    frame $top.cpd54 \
        -borderwidth 2 -relief groove -background {#808080} -height 95 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 135 
    vTcl:DefineAlias "$top.cpd54" "fraYuv" vTcl:WidgetProc "root" 1
    set site_3_0 $top.cpd54
    label $site_3_0.cpd58 \
        -activebackground {#83839999b1b1} -activeforeground black \
        -background {#808080} -disabledforeground {#a3a3a3} -font font10 \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify right -text Y 
    vTcl:DefineAlias "$site_3_0.cpd58" "labYuv_Y" vTcl:WidgetProc "root" 1
    entry $site_3_0.cpd59 \
        -background {#c1ccd9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font11,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable Yuv_Y 
    vTcl:DefineAlias "$site_3_0.cpd59" "entYuv_Y" vTcl:WidgetProc "root" 1
    label $site_3_0.cpd61 \
        -activebackground {#83839999b1b1} -activeforeground black \
        -background {#808080} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify right -text u’ 
    vTcl:DefineAlias "$site_3_0.cpd61" "labYuv_u" vTcl:WidgetProc "root" 1
    entry $site_3_0.cpd62 \
        -background {#c1ccd9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font11,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable Yuv_u 
    vTcl:DefineAlias "$site_3_0.cpd62" "entYuv_u" vTcl:WidgetProc "root" 1
    label $site_3_0.cpd64 \
        -activebackground {#83839999b1b1} -activeforeground black \
        -background {#808080} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify right -text v’ 
    vTcl:DefineAlias "$site_3_0.cpd64" "labYuv_v" vTcl:WidgetProc "root" 1
    entry $site_3_0.cpd65 \
        -background {#c1ccd9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font11,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable Yuv_v 
    vTcl:DefineAlias "$site_3_0.cpd65" "entYuv_v" vTcl:WidgetProc "root" 1
    place $site_3_0.cpd58 \
        -in $site_3_0 -x 2 -y 5 -width 26 -height 19 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd59 \
        -in $site_3_0 -x 30 -y 5 -width 95 -height 20 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd61 \
        -in $site_3_0 -x 2 -y 35 -width 26 -height 19 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd62 \
        -in $site_3_0 -x 30 -y 35 -width 95 -height 20 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd64 \
        -in $site_3_0 -x 2 -y 65 -width 26 -height 19 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd65 \
        -in $site_3_0 -x 30 -y 65 -width 95 -height 20 -anchor nw \
        -bordermode inside 
    button $top.cpd73 \
        -activebackground {#c0c0c0} -activeforeground {#000000} \
        -background {#808080} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#808080} \
        -highlightcolor black -overrelief raised -pady 0 -text {CIE 1931} 
    vTcl:DefineAlias "$top.cpd73" "butCIE1931" vTcl:WidgetProc "root" 1
    button $top.cpd74 \
        -activebackground {#c0c0c0} -activeforeground {#000000} \
        -background {#808080} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#808080} \
        -highlightcolor black -overrelief raised -pady 0 -text {CIE 1976} 
    vTcl:DefineAlias "$top.cpd74" "butCIE1976" vTcl:WidgetProc "root" 1
    frame $top.cpd75 \
        -borderwidth 2 -relief groove -background {#808080} -height 95 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 135 
    vTcl:DefineAlias "$top.cpd75" "fraCIELCHuv" vTcl:WidgetProc "root" 1
    set site_3_0 $top.cpd75
    label $site_3_0.cpd58 \
        -activebackground {#83839999b1b1} -activeforeground black \
        -background {#808080} -disabledforeground {#a3a3a3} -font font10 \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify right -text L* 
    vTcl:DefineAlias "$site_3_0.cpd58" "labLCHuv_L" vTcl:WidgetProc "root" 1
    entry $site_3_0.cpd59 \
        -background {#c1ccd9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font11,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable CLCHuv_L 
    vTcl:DefineAlias "$site_3_0.cpd59" "entLCHuv_L" vTcl:WidgetProc "root" 1
    label $site_3_0.cpd61 \
        -activebackground {#83839999b1b1} -activeforeground black \
        -background {#808080} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify right -text C 
    vTcl:DefineAlias "$site_3_0.cpd61" "labLCHuv_C" vTcl:WidgetProc "root" 1
    entry $site_3_0.cpd62 \
        -background {#c1ccd9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font11,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable CLCHuv_C 
    vTcl:DefineAlias "$site_3_0.cpd62" "entLCHuv_C" vTcl:WidgetProc "root" 1
    label $site_3_0.cpd64 \
        -activebackground {#83839999b1b1} -activeforeground black \
        -background {#808080} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify right -text H° 
    vTcl:DefineAlias "$site_3_0.cpd64" "labLCHuv_H" vTcl:WidgetProc "root" 1
    entry $site_3_0.cpd65 \
        -background {#c1ccd9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font11,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable CLCHuv_H 
    vTcl:DefineAlias "$site_3_0.cpd65" "entLCHuv_H" vTcl:WidgetProc "root" 1
    place $site_3_0.cpd58 \
        -in $site_3_0 -x 2 -y 5 -width 26 -height 19 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd59 \
        -in $site_3_0 -x 30 -y 5 -width 95 -height 20 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd61 \
        -in $site_3_0 -x 2 -y 35 -width 26 -height 19 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd62 \
        -in $site_3_0 -x 30 -y 35 -width 95 -height 20 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd64 \
        -in $site_3_0 -x 2 -y 65 -width 26 -height 19 -anchor nw \
        -bordermode inside 
    place $site_3_0.cpd65 \
        -in $site_3_0 -x 30 -y 65 -width 95 -height 20 -anchor nw \
        -bordermode inside 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra45 \
        -in $top -x 510 -y 340 -width 165 -relwidth 0 -height 65 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra56 \
        -in $top -x 10 -y 10 -width 275 -height 215 -anchor nw \
        -bordermode ignore 
    place $top.cpd39 \
        -in $top -x 150 -y 260 -width 135 -height 95 -anchor nw \
        -bordermode inside 
    place $top.cpd40 \
        -in $top -x 10 -y 260 -width 135 -height 95 -anchor nw \
        -bordermode inside 
    place $top.cpd41 \
        -in $top -x 460 -y 10 -width 105 -height 95 -anchor nw \
        -bordermode inside 
    place $top.cpd42 \
        -in $top -x 570 -y 10 -width 105 -height 95 -anchor nw \
        -bordermode inside 
    place $top.cpd43 \
        -in $top -x 290 -y 210 -width 135 -height 95 -anchor nw \
        -bordermode inside 
    place $top.cpd44 \
        -in $top -x 430 -y 110 -width 135 -height 95 -anchor nw \
        -bordermode inside 
    place $top.cpd45 \
        -in $top -x 150 -y 360 -width 135 -height 95 -anchor nw \
        -bordermode inside 
    place $top.cpd46 \
        -in $top -x 290 -y 110 -width 135 -height 95 -anchor nw \
        -bordermode inside 
    place $top.cpd47 \
        -in $top -x 570 -y 240 -width 105 -height 95 -anchor nw \
        -bordermode inside 
    place $top.cpd48 \
        -in $top -x 570 -y 110 -width 105 -height 125 -anchor nw \
        -bordermode inside 
    place $top.cpd52 \
        -in $top -x 290 -y 10 -width 165 -height 95 -anchor nw \
        -bordermode inside 
    place $top.but37 \
        -in $top -x 690 -y 10 -anchor nw -bordermode ignore 
    place $top.cpd51 \
        -in $top -x 680 -y 90 -width 95 -height 405 -anchor nw \
        -bordermode inside 
    place $top.cpd37 \
        -in $top -x 20 -y 148 -anchor nw -bordermode inside 
    place $top.cpd38 \
        -in $top -x 100 -y 230 -anchor nw -bordermode inside 
    place $top.cpd49 \
        -in $top -x 200 -y 10 -anchor nw -bordermode inside 
    place $top.cpd50 \
        -in $top -x 290 -y 310 -anchor nw -bordermode inside 
    place $top.cpd53 \
        -in $top -x 400 -y 310 -anchor nw -bordermode inside 
    place $top.cpd54 \
        -in $top -x 10 -y 360 -width 135 -height 95 -anchor nw \
        -bordermode inside 
    place $top.cpd73 \
        -in $top -x 690 -y 40 -width 76 -height 24 -anchor nw \
        -bordermode inside 
    place $top.cpd74 \
        -in $top -x 690 -y 70 -width 76 -height 24 -anchor nw \
        -bordermode inside 
    place $top.cpd75 \
        -in $top -x 430 -y 210 -width 135 -height 95 -anchor nw \
        -bordermode inside 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

Window show .
Window show .top41

